window.GALLERY_UI = {
  prevLabel: 'Previous image',
  nextLabel: 'Next image',
  counter: function (i, n) { return 'Image ' + i + ' of ' + n; },
  note: function (total, visible) {
    if (total <= visible) {
      return total + ' photo' + (total === 1 ? '' : 's') + ' · Click to enlarge · Use arrow keys (←/→) or swipe in the viewer';
    }
    return total + ' photos total, ' + visible + ' shown here · In the lightbox, browse all images with arrow keys or swipe';
  },
};
window.JOB_GALLERIES = {
  'profil': [
    { src: '../images/profil.png', caption: 'Slavko Grbic – profile photo (main)', alt: 'Slavko Grbic – profile photo, looking at the camera', label: 'Profile' },
    { src: '../images/profil-casual.png', caption: 'Slavko Grbic – casual profile (polo shirt)', alt: 'Slavko Grbic in a polo shirt, seated, portrait', label: 'Casual' },
    { src: '../images/profil-formal.png', caption: 'Slavko Grbic – formal business portrait', alt: 'Slavko Grbic in a suit and tie, professional portrait', label: 'Business' },
  ],
  'martas': [
    { src: '../images/jobs/martas-hotel/martas-01.png', caption: 'Martas Hotel: gala event – large-scale function for up to 320 guests', alt: 'Martas Hotel – gala event – large-scale function for up to 320 guests', label: 'Gala up to 320 guests' },
    { src: '../images/jobs/martas-hotel/martas-02.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 2/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 2/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-03.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 3/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 3/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-04.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 4/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 4/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-05.png', caption: 'Martas Hotel: conference – meeting room setup', alt: 'Martas Hotel – conference – meeting room setup', label: 'Conference & setup' },
    { src: '../images/jobs/martas-hotel/martas-06.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 6/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 6/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-07.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 7/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 7/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-08.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 8/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 8/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-09.png', caption: 'Martas Hotel: large banquet and gala hall with event lighting (Lutherstadt Wittenberg)', alt: 'Martas Hotel – large banquet and gala hall with event lighting (Lutherstadt Wittenberg)', label: 'Banquet / gala' },
    { src: '../images/jobs/martas-hotel/martas-10.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 10/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 10/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-11.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 11/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 11/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-12.png', caption: 'Restaurant Von Bora: menu card and formal place setting', alt: 'Restaurant Von Bora – menu card and formal place setting', label: 'Von Bora' },
    { src: '../images/jobs/martas-hotel/martas-13.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 13/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 13/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-14.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 14/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 14/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-15.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 15/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 15/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-16.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 16/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 16/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-17.png', caption: 'Martas Hotel: U-shape conference – screen, flipchart, AV preparation', alt: 'Martas Hotel – U-shape conference – screen, flipchart, AV preparation', label: 'AV & U-shape meeting' },
    { src: '../images/jobs/martas-hotel/martas-18.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 18/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 18/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-19.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 19/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 19/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-20.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 20/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 20/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-21.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 21/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – on-the-job impression (photo 21/22)', label: 'Martas Hotel' },
    { src: '../images/jobs/martas-hotel/martas-22.png', caption: 'Stadthalle Lutherstadt Wittenberg: Athletes\' Ball – banquet and stage (annual sports gala)', alt: 'Stadthalle Lutherstadt Wittenberg – Athletes\' Ball – banquet and stage (annual sports gala)', label: 'Athletes\' ball' },
  ],
  'polster': [
    { src: '../images/jobs/polster-catering/polster-01.png', caption: 'Polster Catering: build-up – metal frame of a large tent / pavilion on timber base', alt: 'Polster Catering: build-up – metal frame of a large tent / pavilion on timber base', label: 'Tent frame' },
    { src: '../images/jobs/polster-catering/polster-02.png', caption: 'Polster Catering: team at the bar – uniform, professional service setup', alt: 'Polster Catering: team at the bar – uniform, professional service setup', label: 'Team & bar' },
    { src: '../images/jobs/polster-catering/polster-03.png', caption: 'Polster Catering – large events and logistics (image 3/19)', alt: 'Polster Catering – large events and logistics (image 3/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-04.png', caption: 'Mobile POS (S-600 handheld): orders and table billing', alt: 'Mobile POS (S-600 handheld): orders and table billing', label: 'Mobile POS' },
    { src: '../images/jobs/polster-catering/polster-05.png', caption: 'Polster Catering – large events and logistics (image 5/19)', alt: 'Polster Catering – large events and logistics (image 5/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-06.png', caption: 'Polster Catering – large events and logistics (image 6/19)', alt: 'Polster Catering – large events and logistics (image 6/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-07.png', caption: 'Polster Catering – large events and logistics (image 7/19)', alt: 'Polster Catering – large events and logistics (image 7/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-08.png', caption: 'Large-room seating: conference or gala in the pavilion', alt: 'Large-room seating: conference or gala in the pavilion', label: 'Large-room setup' },
    { src: '../images/jobs/polster-catering/polster-09.png', caption: 'Chemnitz stadium: catering logistics at a major event', alt: 'Chemnitz stadium: catering logistics at a major event', label: 'Chemnitz stadium' },
    { src: '../images/jobs/polster-catering/polster-10.png', caption: 'Polster Catering – large events and logistics (image 10/19)', alt: 'Polster Catering – large events and logistics (image 10/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-11.png', caption: 'Polster Catering – large events and logistics (image 11/19)', alt: 'Polster Catering – large events and logistics (image 11/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-12.png', caption: 'Polster Catering – large events and logistics (image 12/19)', alt: 'Polster Catering – large events and logistics (image 12/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-13.png', caption: 'Polster Catering – large events and logistics (image 13/19)', alt: 'Polster Catering – large events and logistics (image 13/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-14.png', caption: 'Polster Catering – large events and logistics (image 14/19)', alt: 'Polster Catering – large events and logistics (image 14/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-oberhof-01.png', caption: 'Polster Catering · BMW IBU Biathlon World Cup Oberhof (Jan 2017): hospitality tent with set round tables, event branding, view towards the outdoor area', alt: 'Polster Catering · BMW IBU Biathlon World Cup Oberhof (Jan 2017): hospitality tent with set round ta', label: 'Oberhof · VIP tent' },
    { src: '../images/jobs/polster-catering/polster-oberhof-02.png', caption: 'Polster Catering – large events and logistics (image 16/19)', alt: 'Polster Catering – large events and logistics (image 16/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-oberhof-03.png', caption: 'Polster Catering – large events and logistics (image 17/19)', alt: 'Polster Catering – large events and logistics (image 17/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-oberhof-04.png', caption: 'Polster Catering – large events and logistics (image 18/19)', alt: 'Polster Catering – large events and logistics (image 18/19)', label: 'Polster' },
    { src: '../images/jobs/polster-catering/polster-oberhof-05.png', caption: 'Polster Catering – large events and logistics (image 19/19)', alt: 'Polster Catering – large events and logistics (image 19/19)', label: 'Polster' },
  ],
  'amfora': [
    { src: '../images/jobs/amfora-hotel/amfora-01.png', caption: 'Hotel Amfora Hvar: outdoor terrace with set tables, lavender décor, view of the Adriatic and Pakleni Islands', alt: 'Hotel Amfora Hvar: outdoor terrace with set tables, lavender décor, view of the Adriatic a', label: 'Terrace · sea view' },
    { src: '../images/jobs/amfora-hotel/amfora-02.png', caption: 'Hotel Amfora Hvar – pool and outdoor area (impression)', alt: 'Hotel Amfora Hvar – pool and outdoor area (impression)', label: 'Resort' },
    { src: '../images/jobs/amfora-hotel/amfora-03.png', caption: 'Hotel Amfora: pool and terrace area with event/sponsor branding during the Ultra Europe season on Hvar (high guest volume)', alt: 'Hotel Amfora: pool and terrace area with event/sponsor branding during the Ultra Europe se', label: 'Pool · festival week' },
    { src: '../images/jobs/amfora-hotel/amfora-04.png', caption: 'Hotel Amfora Hvar – lobby and bar area (impression)', alt: 'Hotel Amfora Hvar – lobby and bar area (impression)', label: 'Hotel' },
    { src: '../images/jobs/amfora-hotel/amfora-05.png', caption: 'Hotel Amfora: bar with espresso/coffee station, spirits, draught system and POS; open pass to kitchen (FOH/BOH)', alt: 'Hotel Amfora: bar with espresso/coffee station, spirits, draught system and POS; open pass', label: 'Bar · coffee & POS' },
    { src: '../images/jobs/amfora-hotel/amfora-06.png', caption: 'Hotel Amfora Hvar – outdoor grounds (impression)', alt: 'Hotel Amfora Hvar – outdoor grounds (impression)', label: 'Outdoor' },
    { src: '../images/jobs/amfora-hotel/amfora-07.png', caption: 'Hotel Amfora: lobby and lounge area with seating, ice-cream counter and drink coolers – family-friendly resort operation', alt: 'Hotel Amfora: lobby and lounge area with seating, ice-cream counter and drink coolers – fa', label: 'Lobby · lounge' },
  ],
  'javora': [
    { src: '../images/jobs/kod-javora/javora-01.png', caption: 'Restaurant Kod Javora, Osijek: large wooden terrace table on the Drava at dusk – glassware, drinks, espresso: typical end-of-service after a full round', alt: 'Restaurant Kod Javora, Osijek: large wooden terrace table on the Drava at dusk – glassware', label: 'Drava · evening' },
    { src: '../images/jobs/kod-javora/javora-02.png', caption: 'Kod Javora: traditional braising/cooking in large cauldrons over open wood fire – regional home-style cuisine', alt: 'Kod Javora: traditional braising/cooking in large cauldrons over open wood fire – regional', label: 'Fire · cauldron' },
    { src: '../images/jobs/kod-javora/javora-03.png', caption: 'Kod Javora, Osijek – terrace and service (impression)', alt: 'Kod Javora, Osijek – terrace and service (impression)', label: 'Terrace' },
    { src: '../images/jobs/kod-javora/javora-04.png', caption: 'Kod Javora: full evening terrace on the Drava with string lights and parasols (drink-partner branding) – high guest turnover', alt: 'Kod Javora: full evening terrace on the Drava with string lights and parasols (drink-partn', label: 'Evening · peak' },
    { src: '../images/jobs/kod-javora/javora-05.png', caption: 'Kod Javora, Osijek – restaurant and outdoor area (impression)', alt: 'Kod Javora, Osijek – restaurant and outdoor area (impression)', label: 'Kod Javora' },
  ],
  'orfej': [
    { src: '../images/jobs/pizzeria-orfej/orfej-01.png', caption: 'Pizzeria Orfej, Osor: full outdoor terrace under grapevines – high guest turnover, e.g. during sports broadcasts', alt: 'Pizzeria Orfej, Osor: full outdoor terrace under grapevines – high guest turnover, e.g. du', label: 'Terrace · busy' },
    { src: '../images/jobs/pizzeria-orfej/orfej-02.png', caption: 'Pizzeria Orfej: outdoor area with view of the marina and berths – Mediterranean dining, Osor, island of Cres', alt: 'Pizzeria Orfej: outdoor area with view of the marina and berths – Mediterranean dining, Os', label: 'Marina · Terrace' },
    { src: '../images/jobs/pizzeria-orfej/orfej-03.png', caption: 'Pizzeria Orfej: coffee A-board / Julius Meinl on the harbour promenade – guest outreach and daily business', alt: 'Pizzeria Orfej: coffee A-board / Julius Meinl on the harbour promenade – guest outreach an', label: 'Promenade · coffee' },
    { src: '../images/jobs/pizzeria-orfej/orfej-04.png', caption: 'Pizzeria Orfej: covered outdoor terrace with table linen in the stone courtyard – service setup for à-la-carte and pizza', alt: 'Pizzeria Orfej: covered outdoor terrace with table linen in the stone courtyard – service ', label: 'Courtyard · setup' },
  ],
  'vespera': [
    { src: '../images/jobs/hotel-vespera/vespera-01.png', caption: 'Hotel Vespera: family and kids programme on the hotel terrace – DJ, stage, mascot, animation team; typical high-season atmosphere', alt: 'Hotel Vespera: family and kids programme on the hotel terrace – DJ, stage, mascot, animati', label: 'Terrace · animation' },
    { src: '../images/jobs/hotel-vespera/vespera-02.png', caption: 'Hotel Vespera: mascot and playground in the pine forest near the sea – family-friendly resort offering', alt: 'Hotel Vespera: mascot and playground in the pine forest near the sea – family-friendly res', label: 'Playground · kids' },
    { src: '../images/jobs/hotel-vespera/vespera-03.png', caption: 'Hotel Vespera: multi-level pool area with sun loungers, water features and hotel building – central leisure zone of the resort', alt: 'Hotel Vespera: multi-level pool area with sun loungers, water features and hotel building ', label: 'Pool · Resort' },
  ],
  'nock': [
    { src: '../images/jobs/circus-nock/nock-01.png', caption: 'Circus Nock: build-up – entrance stage with illuminated NOCK sign and towers under Swiss flags', alt: 'Circus Nock: build-up – entrance stage with illuminated NOCK sign and towers under Swiss flags', label: 'Build / brand' },
    { src: '../images/jobs/circus-nock/nock-02.png', caption: 'Circus Nock, Switzerland – build and operations (impression 2/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 2/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-03.png', caption: 'Circus Nock, Switzerland – build and operations (impression 3/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 3/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-04.png', caption: 'Circus Nock, Switzerland – build and operations (impression 4/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 4/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-05.png', caption: 'Circus Nock, Switzerland – build and operations (impression 5/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 5/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-06.png', caption: 'Circus Nock: box-office trailer and office/press trailer with NOCK branding', alt: 'Circus Nock: box-office trailer and office/press trailer with NOCK branding', label: 'Box office & office' },
    { src: '../images/jobs/circus-nock/nock-07.png', caption: 'Circus Nock, Switzerland – build and operations (impression 7/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 7/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-08.png', caption: 'Circus Nock, Switzerland – build and operations (impression 8/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 8/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-09.png', caption: 'Circus Nock, Switzerland – build and operations (impression 9/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 9/10)', label: 'Circus Nock' },
    { src: '../images/jobs/circus-nock/nock-10.png', caption: 'Circus Nock, Switzerland – build and operations (impression 10/10)', alt: 'Circus Nock, Switzerland – build and operations (impression 10/10)', label: 'Circus Nock' },
  ],
};
