window.GALLERY_UI = {
  prevLabel: 'Vorheriges Bild',
  nextLabel: 'Nächstes Bild',
  counter: function (i, n) { return 'Bild ' + i + ' von ' + n; },
  note: function (total, visible) {
    if (total <= visible) {
      return total + ' Foto' + (total === 1 ? '' : 's') + ' · Klick zum Vergrößern · In der Ansicht mit Pfeiltasten (←/→) oder Wischen blättern';
    }
    return total + ' Fotos insgesamt, ' + visible + ' hier sichtbar · In der Großansicht alle Bilder mit Pfeiltasten oder Wischen durchblättern';
  },
};
window.JOB_GALLERIES = {
  'martas': [
    { src: 'images/jobs/martas-hotel/martas-01.png', caption: 'Martas Hotel: Gala-Event – Großveranstaltung bis 320 Personen', alt: 'Martas Hotel – Gala-Event – Großveranstaltung bis 320 Personen', label: 'Gala bis 320 Gäste' },
    { src: 'images/jobs/martas-hotel/martas-02.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 2/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 2/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-03.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 3/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 3/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-04.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 4/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 4/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-05.png', caption: 'Martas Hotel: Konferenz – Tagungsraum-Setup', alt: 'Martas Hotel – Konferenz – Tagungsraum-Setup', label: 'Tagung & Setup' },
    { src: 'images/jobs/martas-hotel/martas-06.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 6/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 6/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-07.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 7/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 7/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-08.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 8/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 8/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-09.png', caption: 'Martas Hotel: Großer Bankett- bzw. Gala-Saal mit Eventlicht (Lutherstadt Wittenberg)', alt: 'Martas Hotel – Großer Bankett- bzw. Gala-Saal mit Eventlicht (Lutherstadt Wittenberg)', label: 'Bankett / Gala' },
    { src: 'images/jobs/martas-hotel/martas-10.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 10/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 10/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-11.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 11/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 11/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-12.png', caption: 'Restaurant Von Bora: Menükarte und formelles Gedeck', alt: 'Restaurant Von Bora – Menükarte und formelles Gedeck', label: 'Von Bora' },
    { src: 'images/jobs/martas-hotel/martas-13.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 13/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 13/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-14.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 14/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 14/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-15.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 15/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 15/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-16.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 16/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 16/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-17.png', caption: 'Martas Hotel: Tagung in U-Form – Leinwand, Flipchart, AV-Vorbereitung', alt: 'Martas Hotel – Tagung in U-Form – Leinwand, Flipchart, AV-Vorbereitung', label: 'AV & U-Tagung' },
    { src: 'images/jobs/martas-hotel/martas-18.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 18/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 18/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-19.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 19/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 19/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-20.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 20/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 20/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-21.png', caption: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 21/22)', alt: 'Martas Hotel, Lutherstadt Wittenberg – Betriebsimpression (Foto 21/22)', label: 'Martas Hotel' },
    { src: 'images/jobs/martas-hotel/martas-22.png', caption: 'Stadthalle Lutherstadt Wittenberg: Wittenberger Sportlerball – Bankett und Bühne (jährliche Sportlergala)', alt: 'Stadthalle Lutherstadt Wittenberg – Wittenberger Sportlerball – Bankett und Bühne (jährliche Sportlergala)', label: 'Sportlerball' },
  ],
  'polster': [
    { src: 'images/jobs/polster-catering/polster-01.png', caption: 'Polster Catering: Aufbau – Metallgerüst eines großen Zeltes / Pavillons auf Holzunterbau', alt: 'Polster Catering: Aufbau – Metallgerüst eines großen Zeltes / Pavillons auf Holzunterbau', label: 'Zelt-Gerüst' },
    { src: 'images/jobs/polster-catering/polster-02.png', caption: 'Polster Catering: Team an der Bar – Uniform, professionelles Service-Setup', alt: 'Polster Catering: Team an der Bar – Uniform, professionelles Service-Setup', label: 'Team & Bar' },
    { src: 'images/jobs/polster-catering/polster-03.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 3/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 3/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-04.png', caption: 'Mobiles POS (S-600 Handy): Bestellungen und Tischabrechnung', alt: 'Mobiles POS (S-600 Handy): Bestellungen und Tischabrechnung', label: 'Mobiles POS' },
    { src: 'images/jobs/polster-catering/polster-05.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 5/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 5/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-06.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 6/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 6/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-07.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 7/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 7/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-08.png', caption: 'Großraum-Bestuhlung: Tagung oder Gala im Pavillon', alt: 'Großraum-Bestuhlung: Tagung oder Gala im Pavillon', label: 'Großraum-Setup' },
    { src: 'images/jobs/polster-catering/polster-09.png', caption: 'Stadion Chemnitz: Catering-Logistik bei Großveranstaltung', alt: 'Stadion Chemnitz: Catering-Logistik bei Großveranstaltung', label: 'Stadion Chemnitz' },
    { src: 'images/jobs/polster-catering/polster-10.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 10/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 10/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-11.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 11/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 11/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-12.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 12/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 12/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-13.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 13/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 13/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-14.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 14/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 14/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-oberhof-01.png', caption: 'Polster Catering · BMW IBU Weltcup Biathlon Oberhof (Jan. 2017): Hospitality-Zelt mit gedeckten Rundtischen, Eventbranding, Blick zur Außenlage', alt: 'Polster Catering · BMW IBU Weltcup Biathlon Oberhof (Jan. 2017): Hospitality-Zelt mit gedeckten Rund', label: 'Oberhof · VIP-Zelt' },
    { src: 'images/jobs/polster-catering/polster-oberhof-02.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 16/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 16/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-oberhof-03.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 17/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 17/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-oberhof-04.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 18/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 18/19)', label: 'Polster' },
    { src: 'images/jobs/polster-catering/polster-oberhof-05.png', caption: 'Polster Catering – Großveranstaltung und Logistik (Motiv 19/19)', alt: 'Polster Catering – Großveranstaltung und Logistik (Motiv 19/19)', label: 'Polster' },
  ],
  'amfora': [
    { src: 'images/jobs/amfora-hotel/amfora-01.png', caption: 'Hotel Amfora Hvar: Außen-Terrasse mit gedeckten Tischen, Lavendel-Dekor, Blick auf Adria und Pakleni-Inseln', alt: 'Hotel Amfora Hvar: Außen-Terrasse mit gedeckten Tischen, Lavendel-Dekor, Blick auf Adria u', label: 'Terrasse · Meerblick' },
    { src: 'images/jobs/amfora-hotel/amfora-02.png', caption: 'Hotel Amfora Hvar – Pool- und Außenbereich (Impression)', alt: 'Hotel Amfora Hvar – Pool- und Außenbereich (Impression)', label: 'Resort' },
    { src: 'images/jobs/amfora-hotel/amfora-03.png', caption: 'Hotel Amfora: Pool- und Terrassenbereich mit Event-/Sponsor-Branding während der Ultra-Europe-Saison auf Hvar (hohes Gästeaufkommen)', alt: 'Hotel Amfora: Pool- und Terrassenbereich mit Event-/Sponsor-Branding während der Ultra-Eur', label: 'Pool · Festivalzeit' },
    { src: 'images/jobs/amfora-hotel/amfora-04.png', caption: 'Hotel Amfora Hvar – Lobby- und Barbereich (Impression)', alt: 'Hotel Amfora Hvar – Lobby- und Barbereich (Impression)', label: 'Hotel' },
    { src: 'images/jobs/amfora-hotel/amfora-05.png', caption: 'Hotel Amfora: Bar mit Espresso-/Kaffee-Station, Spirituosen, Zapfanlage und POS; offener Übergang zur Küche (FOH/BOH)', alt: 'Hotel Amfora: Bar mit Espresso-/Kaffee-Station, Spirituosen, Zapfanlage und POS; offener Ü', label: 'Bar · Kaffee & POS' },
    { src: 'images/jobs/amfora-hotel/amfora-06.png', caption: 'Hotel Amfora Hvar – Außenanlage (Impression)', alt: 'Hotel Amfora Hvar – Außenanlage (Impression)', label: 'Außenbereich' },
    { src: 'images/jobs/amfora-hotel/amfora-07.png', caption: 'Hotel Amfora: Lobby- bzw. Loungebereich mit Sitzlandschaft, Eis-Theke und Getränkekühlung – familienfreundlicher Resort-Betrieb', alt: 'Hotel Amfora: Lobby- bzw. Loungebereich mit Sitzlandschaft, Eis-Theke und Getränkekühlung ', label: 'Lobby · Lounge' },
  ],
  'javora': [
    { src: 'images/jobs/kod-javora/javora-01.png', caption: 'Restaurant Kod Javora Osijek: große Holz-Terrassentafel an der Drau im Abendlicht – Glasware, Getränke, Espresso: typischer Service-Ende einer vollen Runde', alt: 'Restaurant Kod Javora Osijek: große Holz-Terrassentafel an der Drau im Abendlicht – Glaswa', label: 'Drau · Abendservice' },
    { src: 'images/jobs/kod-javora/javora-02.png', caption: 'Kod Javora: traditionelles Schmoren/Kochen in großen Kesseln über offenem Holzfeuer – regionale Hausküche', alt: 'Kod Javora: traditionelles Schmoren/Kochen in großen Kesseln über offenem Holzfeuer – regi', label: 'Feuer · Kessel' },
    { src: 'images/jobs/kod-javora/javora-03.png', caption: 'Kod Javora, Osijek – Terrasse und Service (Impression)', alt: 'Kod Javora, Osijek – Terrasse und Service (Impression)', label: 'Terrasse' },
    { src: 'images/jobs/kod-javora/javora-04.png', caption: 'Kod Javora: volle Abend-Terrasse an der Drau mit Lichterketten und Sonnenschirmen (Markenaufdruck Getränkepartner) – hoher Gästedurchsatz', alt: 'Kod Javora: volle Abend-Terrasse an der Drau mit Lichterketten und Sonnenschirmen (Markena', label: 'Abend · Hochbetrieb' },
    { src: 'images/jobs/kod-javora/javora-05.png', caption: 'Kod Javora, Osijek – Restaurant und Außenbereich (Impression)', alt: 'Kod Javora, Osijek – Restaurant und Außenbereich (Impression)', label: 'Kod Javora' },
  ],
  'orfej': [
    { src: 'images/jobs/pizzeria-orfej/orfej-01.png', caption: 'Pizzeria Orfej Osor: volle Außen-Terrasse unter Weinlaub – hoher Gästedurchsatz, u.a. bei Sportübertragung am Fernseher', alt: 'Pizzeria Orfej Osor: volle Außen-Terrasse unter Weinlaub – hoher Gästedurchsatz, u.a. bei ', label: 'Terrasse · Hochbetrieb' },
    { src: 'images/jobs/pizzeria-orfej/orfej-02.png', caption: 'Pizzeria Orfej: Außenbereich mit Blick auf Marina und Liegeplätze – mediterraner Gastro-Betrieb Osor, Insel Cres', alt: 'Pizzeria Orfej: Außenbereich mit Blick auf Marina und Liegeplätze – mediterraner Gastro-Be', label: 'Marina · Terrasse' },
    { src: 'images/jobs/pizzeria-orfej/orfej-03.png', caption: 'Pizzeria Orfej: Außenaufsteller Kaffee / Julius Meinl an der Hafenpromenade – Gästeansprache und Tagesgeschäft', alt: 'Pizzeria Orfej: Außenaufsteller Kaffee / Julius Meinl an der Hafenpromenade – Gästeansprac', label: 'Promenade · Kaffee' },
    { src: 'images/jobs/pizzeria-orfej/orfej-04.png', caption: 'Pizzeria Orfej: gedeckte Außen-Terrasse mit Tischwäsche im steinernen Innenhof – Service-Setup für À-la-carte und Pizza', alt: 'Pizzeria Orfej: gedeckte Außen-Terrasse mit Tischwäsche im steinernen Innenhof – Service-S', label: 'Hof · Gedeck' },
  ],
  'vespera': [
    { src: 'images/jobs/hotel-vespera/vespera-01.png', caption: 'Hotel Vespera: Familien- und Kinderprogramm auf der Hotelterrasse – DJ, Bühne, Maskottchen, Animationsteam; typische Hochsaison-Atmosphäre', alt: 'Hotel Vespera: Familien- und Kinderprogramm auf der Hotelterrasse – DJ, Bühne, Maskottchen', label: 'Terrasse · Animation' },
    { src: 'images/jobs/hotel-vespera/vespera-02.png', caption: 'Hotel Vespera: Maskottchen und Spielplatz im Kiefernwald nahe Meer – familienfreundliches Resort-Angebot', alt: 'Hotel Vespera: Maskottchen und Spielplatz im Kiefernwald nahe Meer – familienfreundliches ', label: 'Spielplatz · Kids' },
    { src: 'images/jobs/hotel-vespera/vespera-03.png', caption: 'Hotel Vespera: mehrstufiges Pool-Areal mit Liegen, Wasserspielen und Hotelgebäude – zentrale Freizeitzone des Resorts', alt: 'Hotel Vespera: mehrstufiges Pool-Areal mit Liegen, Wasserspielen und Hotelgebäude – zentra', label: 'Pool · Resort' },
  ],
  'nock': [
    { src: 'images/jobs/circus-nock/nock-01.png', caption: 'Circus Nock: Aufbau – Eingangsbühne mit Leuchtschrift NOCK und Türmen unter Schweizerfahnen', alt: 'Circus Nock: Aufbau – Eingangsbühne mit Leuchtschrift NOCK und Türmen unter Schweizerfahnen', label: 'Aufbau / Marke' },
    { src: 'images/jobs/circus-nock/nock-02.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 2/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 2/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-03.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 3/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 3/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-04.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 4/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 4/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-05.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 5/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 5/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-06.png', caption: 'Circus Nock: Kassen-Trailer «KASSE» und Büro-/Presse-Trailer mit Schriftzug NOCK', alt: 'Circus Nock: Kassen-Trailer «KASSE» und Büro-/Presse-Trailer mit Schriftzug NOCK', label: 'Kasse & Büro' },
    { src: 'images/jobs/circus-nock/nock-07.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 7/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 7/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-08.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 8/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 8/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-09.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 9/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 9/10)', label: 'Circus Nock' },
    { src: 'images/jobs/circus-nock/nock-10.png', caption: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 10/10)', alt: 'Circus Nock, Schweiz – Aufbau und Betrieb (Impression 10/10)', label: 'Circus Nock' },
  ],
};
